---
- name: Install nginx latest version
  apt:
    name: nginx
    state: latest
    update_cache: yes

- name: Update main nginx config
  copy:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf
    owner: root
    group: root
    mode: '0644'
    backup: yes

- name:  Check config nginx
  command: "nginx -t"
  register: check_nginx_config
  ignore_errors: True

- name:  Error Message when check config nginx fail
  fail:
    msg: "{{ inventory_hostname }} has error nginx config"
  when: check_nginx_config.rc != 0
  
- name:  Reload nginx if check config successfully
  systemd:
    name: nginx
    state: restarted
    enabled: yes
  when: check_nginx_config.rc == 0
