---
- name: Install zabbix apt repo
  apt:
    deb: https://repo.zabbix.com/zabbix/5.4/ubuntu/pool/main/z/zabbix-release/zabbix-release_5.4-1+ubuntu20.04_all.deb

- name: Install package zabbix-agent2
  apt:
    name: zabbix-agent2
    update_cache: yes

- name: Update zabbix-agent2 config
  template:
    src: zabbix_agent2.j2
    dest: /etc/zabbix/zabbix_agent2.conf
    owner: root
    group: root
    mode: '0644'

- name: Restart zabbix-agent2 service
  systemd:
    name: zabbix-agent2
    enabled: yes
    state: restarted

- name: Allow zabbix-server access port zabbix-agent
  ufw:
    rule: allow
    proto: tcp
    src: 10.30.20.11
    port: '10050'