---
- name: Web Backend | Create groupuser deploy
  group:
    name: deploy
    state: present

- name: Web Backend | Create user deploy
  user:
    name: deploy
    shell: /bin/bash
    group: deploy
    home: /home/deploy
    create_home: yes
    generate_ssh_key: yes

- name: Web Backend | Show git branch on bash shell
  blockinfile:
    path: /home/deploy/.bashrc
    block: |
      git_branch() {
        git branch 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/(\1)/'
      }

      export PS1='\u@\h\[\033[00m\]:\[\033[01;34m\]\W\[\033[01;31m\] $(git_branch)\[\033[00m\]\$ '

- name: Web Backend | Create folder /data/www if roles backend
  file:
    path: /data/www
    state: directory
    owner: deploy
    group: deploy
