---

- include_tasks: add_user.yml
  with_items:
    - "{{ users }}"
  when:
    - item.servers
    - inventory_hostname in item.servers

- include_tasks: add_publish_key.yml
  with_subelements:
    - "{{ users }}"
    - authorized_keys
  when:
    - item.0.servers
    - inventory_hostname in item.0.servers

- include_tasks: remove_user.yml
  when:
    - absent_users
