---
- name: Update SSHD Config
  copy:
    src: sshd_config
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: '0644'

- name: Allow access sshd port with limit
  ufw:
    rule: limit
    proto: tcp
    port: '1122'

- name: Restart sshd service
  systemd:
    name: sshd
    enabled: yes
    state: restarted